[functions]
  included_files = ["serverless/*.liquid", "serverless/lib/*.liquid"]

[build]
  command = "npm run build"
  publish = "dist"
  functions = "serverless"
  NODE_ENV = "16.9.1"

[dev]
  command = "npm run dev"
  autoLaunch = false

[[redirects]]
  from = "/jobs/"
  to = "/404"
  status = 404

[[redirects]]
  from = "/jobs/*"
  to = "/.netlify/functions/getJob"
  status = 200